### ISSUE TITLE
src of chapter wrong

### ISSUE THREAD

**Issue by veila** [f-meloni/epubExtractor#2]
SRC of chapter wrong, no folder "toc.ncx" but this is path of chapter when unzip
"/Library/Developer/CoreSimulator/Devices/E98CF576-FB3B-40F9-8645-D991102AFF11/data/Containers/Data/Application/78C373F2-6B93-47F0-9AF1-01ED0B050742/Documents/Metamorphosis-jackson/toc.ncx/OEBPS/front-cover.html"
Please fix

**Comment by f-meloni** [comment]
https://github.com/f-meloni/epubExtractor/commit/e38bac1a60ff523b0b669f6bfcb88952cfecc1d4
Should fix it

**Comment by f-meloni** [comment]
Feel free to reopen the issue if the problem is still there
